ci: update workflows
Flash0ver/F0.Analyzers pull request #109
Opened 2023-09-18 22:44 UTC by Flash0ver

2023-09-20 10:38 UTC, NKnusperer requested changes
`windows-2022` is broken :(

2023-09-20 18:56 UTC, Flash0ver commented on .github/workflows/build-vsix.yml
> +        vs-version: '[17.0,18.0)'
The _Build_ step is failing due to warnings as errors, with a false positive on [CA1825](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1825).

The false positive is reported on usages of the attributes
- [DiagnosticAnalyzerAttribute](https://learn.microsoft.com/dotnet/api/microsoft.codeanalysis.diagnostics.diagnosticanalyzerattribute.-ctor)
- [ExportCodeFixProviderAttribute](https://learn.microsoft.com/dotnet/api/microsoft.codeanalysis.codefixes.exportcodefixproviderattribute.-ctor)
- [ExportCodeRefactoringProviderAttribute](https://learn.microsoft.com/dotnet/api/microsoft.codeanalysis.coderefactorings.exportcoderefactoringproviderattribute.-ctor)

invoked like

```CSharp
[DiagnosticAnalyzer(LanguageNames.CSharp)]
[ExportCodeFixProvider(LanguageNames.CSharp, Name = nameof(MyCodeFixProvider))]
[ExportCodeRefactoringProvider(LanguageNames.CSharp, Name = nameof(MyCodeRefactoringProvider))]
```

where we explicitly pass the argument `LanguageNames.CSharp` to the first parameter `string firstLanguage` of the attribute constructor, but we implicitly pass the argument `call !!0[] [System.Runtime]System.Array::Empty<string>()` to the second "params" parameter `params string[] additionalLanguages` of the attribute constructor.

I hope to be able to just "merge it off" via #106.

2023-09-21 08:12 UTC, TimoHeiten approved these changes

2023-09-21 08:42 UTC, NKnusperer approved these changes

2023-09-23 08:10 UTC, NKnusperer approved these changes

2023-10-02 07:30 UTC, Flash0ver commented on .github/workflows/build-vsix.yml
> +        vs-version: '[17.0,18.0)'
Was fixed with the merge indeed.

2024-01-22 01:26 UTC, merged